name: Deploy

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push turbo-pnpm-base-image to Docker Hub
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build --pull -t ${{ secrets.DOCKER_USERNAME }}/turbo-pnpm-base-image:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/turbo-pnpm-base-image:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/turbo-pnpm-base-image:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/turbo-pnpm-base-image:latest
